{
  "sksl": {
    "entrypoint": "dots_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uSeed;\nuniform vec4 uColor;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_f_(float t)\n{\n    float ff = (fract(t / 8.0) * 4.0) - 2.0;\n    return abs(smoothstep(0.0, 0.5, fract(ff) - 0.25) + floor(ff)) - 1.0;\n}\n\nfloat FLT_flutter_local_dist_field(vec2 p)\n{\n    float d = 0.0;\n    float t = -uSeed;\n    for (float i = 0.0; i < 7.0; i += 1.0)\n    {\n        float a = ((0.157079637050628662109375 * i) * 2.0) + (t * 2.0);\n        float param = a;\n        d += (1.0 / length(p + vec2(FLT_flutter_local_f_(param), 0.0)));\n    }\n    return d;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = ((flutter_FragCoord.xy / uSize) * 2.0) - vec2(1.0);\n    uv.x *= 3.0;\n    float zoom = 0.4000000059604644775390625;\n    uv *= zoom;\n    vec2 param_1 = uv;\n    float d_1 = (FLT_flutter_local_dist_field(param_1) / 3.0) - 10.0;\n    float intensity = clamp(d_1, 0.0, 1.0);\n    fragColor = vec4(uColor.xyz * intensity, intensity * uColor.w);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSeed",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}